[project]
name = "btc-prediction-market"
description = "Bitcoin-Anchored Prediction Market using Clarity 4"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.sip-010-trait-v4]
path = "contracts/sip-010-trait-v4.clar"
clarity_version = 3
epoch = 3.0

[contracts.btc-prediction-market-v4]
path = "contracts/stx-pred-market-v4.clar"
clarity_version = 3
epoch = 3.0
depends_on = ["sip-010-trait-v4"]

[contracts.prediction-token-v4]
path = "contracts/pred-token-v4.clar"
clarity_version = 3
epoch = 3.0
depends_on = ["sip-010-trait-v4"]

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
